multiplexer = "tmux"

picker = '''
sesh list --icons | fzf-tmux -p 80%,70% \
  --no-sort --ansi --border-label ' sesh ' --prompt 'âš¡  ' \
  --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
  --bind 'tab:down,btab:up' \
  --bind 'ctrl-a:change-prompt(âš¡  )+reload(sesh list --icons)' \
  --bind 'ctrl-t:change-prompt(ğŸªŸ  )+reload(sesh list -t --icons)' \
  --bind 'ctrl-g:change-prompt(âš™ï¸  )+reload(sesh list -c --icons)' \
  --bind 'ctrl-x:change-prompt(ğŸ“  )+reload(sesh list -z --icons)' \
  --bind 'ctrl-f:change-prompt(ğŸ”  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
  --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(âš¡  )+reload(sesh list --icons)' \
  --preview-window 'right:55%' \
  --preview 'sesh preview {}'
'''

# Git detector
[[detectors]]
kind = "git"
dirs = ["~/.config", "~/Documents/Projects", "~/Documents/srew-softwares"]

# Define a default session template as a real session
[[sessions]]
name = "default"
root = "~"

[[sessions.windows]]
name = "vim"
command = "nvim"

[[sessions.windows]]
name = "shell"
command = "zsh"

[[sessions.windows]]
name = "agent"
command = "gemini"

[[sessions.windows]]
name = "dev"
command = "npm run dev"
when_files = ["package.json"]

[[sessions.windows]]
name = "dev-go"
command = "go run ."
when_files = ["go.mod"]
